#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab


"""csv2ynab: Converts Revolut & Paypal csv files to an acceptable format for input to YNAB."""

from __future__ import absolute_import, print_function

#from sys import stdin, stdout
import sys
import csv
from argparse import RawTextHelpFormatter, ArgumentParser
import datetime



import itertools as it

from meza.io import read_csv, IterStringIO
from csv2ofx import utils
from csv2ofx.ofx import OFX
from csv2ofx.mappings.default import mapping

#import locale
#from decimal import Decimal

BASE_CURRENCY = 'GBP'

YNAB_HEADER_DATE = 'Date'
YNAB_HEADER_PAYEE = 'Payee'
YNAB_HEADER_CATEGORY = 'Category'
YNAB_HEADER_MEMO = 'Memo'
YNAB_HEADER_OUTFLOW = 'Outflow'
YNAB_HEADER_INFLOW = 'Inflow'

REVOLUT_HEADER_DATE = 'Completed Date'
REVOLUT_HEADER_PAYEE = 'Reference'
REVOLUT_HEADER_CATEGORY = 'Category'
REVOLUT_HEADER_OUTFLOW = 'Paid Out (GBP)'
REVOLUT_HEADER_INFLOW = 'Paid In (GBP)'
REVOLUT_IDENTIFIER_KEY = REVOLUT_HEADER_DATE

PAYPAL_HEADER_DATE = 'Date'
PAYPAL_HEADER_PAYEE = ' Name'
PAYPAL_HEADER_TYPE = ' Type'
PAYPAL_HEADER_MEMO = ' Item Title'
PAYPAL_HEADER_NET = ' Net'
PAYPAL_HEADER_CURRENCY = ' Currency'
PAYPAL_HEADER_STATUS = ' Status'
PAYPAL_HEADER_REF_TRANS = ' Reference Txn ID'
PAYPAL_HEADER_TRANS_ID = ' Transaction ID'

PAYPAL_IDENTIFIER_KEY = ' Counterparty Status'


parser = ArgumentParser(description="description: csv2ynab processes Revolut & PayPal csv files for import into YNAB",
                        prog='csv2ynab', usage='%(prog)s [options] <source> <dest>',
                        formatter_class=RawTextHelpFormatter)

parser.add_argument(dest='source', nargs='?', help='the .csv file to process')
parser.add_argument(dest='dest', nargs='?', help='the output file (defaults to stdout)')
parser.add_argument('-c', '--category', action='count', help='Fill in the category field')
parser.add_argument('-m', '--memo', action='count', help='Fill in the Memo field with Exchange info')
parser.add_argument('-t', '--topup', action='count', help='Skip Top-Up & Auto Top-Up entries')
parser.add_argument('-E', '--encoding', default='utf-8', help="File encoding (default: utf-8)")
parser.add_argument('-V', '--version', help="show version and exit", action='store_true', default=False)



args = parser.parse_args()

results = []
YNAB_FIELDNAMES = [YNAB_HEADER_DATE, YNAB_HEADER_PAYEE, YNAB_HEADER_CATEGORY, YNAB_HEADER_MEMO, YNAB_HEADER_OUTFLOW, YNAB_HEADER_INFLOW]


class baseCSV:

    def __init__(self, args, reader, writer):
        self.args = args
        self.reader = reader
        self.writer = writer

    def isBankTopUp(self, row):
        return False

    def absAmount(self, value):
        if value[:1] == '-':
            value = value[1:]
        return value

    def processCurrency(self, amount):
        """ Remove the comma in n,nnn.nn"""
        return amount.replace(',','')

    def writeHeader(self):
         self.writer.writeheader()


    def writeRow(self, y_row):
        # Remove ',' from currency amounts
        y_row[YNAB_HEADER_OUTFLOW] = self.processCurrency(y_row[YNAB_HEADER_OUTFLOW])
        y_row[YNAB_HEADER_INFLOW] = self.processCurrency(y_row[YNAB_HEADER_INFLOW])

        self.writer.writerow(y_row)

    def Convert(self):
        print("")



class RevolutCSV(baseCSV):

    def __init__(self, args, reader, write):
        baseCSV.__init__(self, args, reader, writer)

    def isBankTopUp(self, row):
        payee = row[REVOLUT_HEADER_PAYEE]
        return payee[:6] == 'Top-Up' or payee[:11] == 'Auto Top-Up'

    def ProcessCurrency(self, amount):
        """ Remove the comma in n,nnn.nn"""
        return amount.replace(',','')

#        if amount == '':
#            return ''
#        return Decimal(amount)

    def Convert(self):
        self.writeHeader()

        for r_row in self.reader:

            if self.args.topup and self.isBankTopUp(r_row):
                continue

            y_row = {}
            # Do Date
            r_date = r_row[REVOLUT_HEADER_DATE]
            y_date = datetime.datetime.strptime(r_date, '%d %B %Y')
            y_date = (datetime.date.strftime(y_date, "%d/%m/%Y"))
            y_row[YNAB_HEADER_DATE] = y_date

            # Payee
            y_row[YNAB_HEADER_PAYEE] = r_row[REVOLUT_HEADER_PAYEE]

            # Category

            if self.args.category:
                y_row[YNAB_HEADER_CATEGORY] = r_row[REVOLUT_HEADER_CATEGORY]
            else:
                y_row[YNAB_HEADER_CATEGORY] = ''

            # Memo
            if self.args.memo:
                y_row[YNAB_HEADER_MEMO] = r_row['Exchange Out'] + r_row['Exchange In']
            else:
                y_row[YNAB_HEADER_MEMO] = ''

            # Inflow, Outflow

            y_row[YNAB_HEADER_INFLOW] = self.ProcessCurrency(r_row[REVOLUT_HEADER_INFLOW])
            y_row[YNAB_HEADER_OUTFLOW] = self.ProcessCurrency(r_row[REVOLUT_HEADER_OUTFLOW])


            self.writeRow(y_row)



class RevolutOFX(baseCSV):
    def __init__(self, args, reader, write):
        baseCSV.__init__(self, args, reader, writer)

    def Convert(self):
        ofx = OFX(mapping)
#        records = self.reader.rows
#        groups = ofx.gen_groups(records)
#        trxns = ofx.gen_trxns(groups)
#        cleaned_trxns = ofx.clean_trxns(trxns)
#        data = utils.gen_data(cleaned_trxns)
#        content = it.chain([ofx.header(), ofx.gen_body(data), ofx.footer()])

#        for line in IterStringIO(content):
#            print(line)


class PaypalCSV(baseCSV):
    def __init__(self, args, reader, writer):
        baseCSV.__init__(self, args, reader, writer)

    def isCompleted(self, row):
        return row[PAYPAL_HEADER_STATUS] == 'Completed'

    def isBankTopUp(self, row):
        return row[PAYPAL_HEADER_PAYEE] == 'Bank Account' and row[PAYPAL_HEADER_TYPE] == 'Add Money from a Bank Account'

    def isTemporaryHold(self, row):
        return row[PAYPAL_HEADER_PAYEE] == 'PayPal' and row[PAYPAL_HEADER_TYPE] == "Temporary Hold" and \
            not self.isCompleted(row)

    def isPendingBalancePayment(self, row):
        return row[PAYPAL_HEADER_PAYEE] == 'PayPal' and row[PAYPAL_HEADER_TYPE] == "Pending Balance Payment" and \
            not self.isCompleted(row)

    def isCurrencyConversion(self, row):
        return row[PAYPAL_HEADER_TYPE] == 'Currency Conversion'

    def isBaseCurrency(self, row):
        return row[PAYPAL_HEADER_CURRENCY] == BASE_CURRENCY

    def Convert(self):
        self.writeHeader()
        trans_id = '?????????????'

        for p_row in self.reader:

            if self.isPendingBalancePayment(p_row):
                continue

            if self.args.topup and self.isBankTopUp(p_row):
                continue

            if self.isTemporaryHold(p_row):
                continue

            if self.isCurrencyConversion(p_row):
                if self.isBaseCurrency(p_row):
                    trans_id = p_row[PAYPAL_HEADER_REF_TRANS]
                    base_amount = p_row[PAYPAL_HEADER_NET]
                continue


            y_row = {}
            # Do Date
            y_row[YNAB_HEADER_DATE] = p_row[PAYPAL_HEADER_DATE]

            y_row[YNAB_HEADER_PAYEE] = p_row[PAYPAL_HEADER_PAYEE]
            y_row[YNAB_HEADER_CATEGORY] = ''

            if self.args.memo:
                y_row[YNAB_HEADER_MEMO] = p_row[PAYPAL_HEADER_MEMO]
            else:
                y_row[YNAB_HEADER_MEMO] = ''

            y_row[YNAB_HEADER_OUTFLOW] = ''
            if p_row[PAYPAL_HEADER_TRANS_ID] == trans_id:
                y_row[YNAB_HEADER_INFLOW] = base_amount
                y_row[YNAB_HEADER_MEMO] = y_row[YNAB_HEADER_MEMO] + \
                    " (" + self.absAmount(p_row[PAYPAL_HEADER_NET]) + p_row[PAYPAL_HEADER_CURRENCY] + ")"
                trans_id = '?????????????'
                base_amount = ''
            else:
                y_row[YNAB_HEADER_INFLOW] = p_row[PAYPAL_HEADER_NET]

            self.writeRow(y_row)



def run():  # noqa: C901
    """Parses the CLI options and runs the main program
    """

    if args.version:
        from . import __version__ as version
        print('v%s' % version)
        exit(0)

    source = open(args.source, encoding=args.encoding) if args.source else sys.stdin

#    with open(args.source, newline='') as source:
        # Check we've got a header line

    try:
        if not csv.Sniffer().has_header(source.read(1024)):
            print ("ERROR: s does not appear to have a header line.", file=sys.stderr)
            exit(1)
        source.seek(0)

        # Get some basic csv file info
        dialect = csv.Sniffer().sniff(source.read(1024))

        source.seek(0)

        # Start reading the file
        reader = csv.DictReader(source, delimiter=dialect.delimiter)
    except Exception as err:  # pylint: disable=broad-except
        source.close()
        exit(err)

    try:
        dest = open(args.dest, 'w', encoding=args.encoding) if args.dest else sys.stdout

        writer = csv.DictWriter(dest, YNAB_FIELDNAMES)

        if REVOLUT_IDENTIFIER_KEY in reader.fieldnames:
            csv_processor = RevolutCSV(args, reader, writer)
    #        csv_processor = RevolutOFX(args, reader, writer)
        elif PAYPAL_IDENTIFIER_KEY in reader.fieldnames:
            csv_processor = PaypalCSV(args, reader, writer)
        else:
            print("ERROR: Unrecognised file format.", file=sys.stderr)
            exit(1)

        csv_processor.Convert()
    finally:
#        exit(1)
        source.close() if args.source else None
        dest.close() if args.dest else None



if __name__ == '__main__':
    run()
